POST http://127.0.0.1:8000/authentication/signup 
Content-Type: application/json

{ "username": "matt123", "password": "password1234!", "email": "matt@mail.com" }

###

POST http://127.0.0.1:8000/authentication/login 
Content-Type: application/json

{ "username": "matt123", "password": "password1234!" }

###

GET http://127.0.0.1:8000/authentication/test_token 
Content-Type: application/json 
Authorization: token 1ca8fca0a3141ab6e40e378ddd1f5c9f089c03bf

###

POST http://127.0.0.1:8000/authentication/logout
Content-Type: application/json
Authorization: token acf31075fe1291de461638c6d7f69f05437ad3d5

###

POST http://127.0.0.1:8000/timetracker/create_project
Content-Type: application/json

{}

